name: Go test

on: [push]

jobs:
  test-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.17', '1.18', '1.19', '1.20', '1.21' ]
        mongodb-version: [ '4.4', '5.0', '6.0', '7.0' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@v1
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: mgm-rs
          mongodb-db: mgmdb

      - run: go test ./...
